import type { Challenge } from "./ChallengeCard";

export const CHALLENGES: Challenge[] = [
  {
    id: 1,
    title: "CW 10K Run",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=300&fit=crop",
    date: "Sat, Aug 16 · 9:00 AM",
    location: "Hyde Park, London",
    fee: 25,
    spotsLeft: 12,
    status: "limited",
    registerHref: "/challenges/register/1",
    tags: ["CW 10k Runs", "Imperial ISOC", "London", "Team: Imperial Sisters"],
    fundraisingGoal: 50000,
  },
  {
    id: 2,
    title: "CW 10K Run",
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400&h=300&fit=crop",
    date: "Sat, Aug 16 · 9:00 AM",
    location: "Hyde Park, London",
    fee: 25,
    spotsLeft: 40,
    status: "available",
    registerHref: "/challenges/register/2",
    tags: ["CW 10k Runs", "Hyde Park", "London", "Team: Sunrise Runners"],
    fundraisingGoal: 50000,
  },
  {
    id: 3,
    title: "CW 10K Run",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&h=300&fit=crop",
    date: "Sat, Aug 16 · 9:00 AM",
    location: "Hyde Park, London",
    fee: 25,
    spotsLeft: 6,
    status: "few",
    registerHref: "/challenges/register/3",
    tags: ["CW 10k Runs", "Hyde Park", "London"],
    fundraisingGoal: 30000,
  },
  {
    id: 4,
    title: "CW 10K Run",
    image: "https://images.unsplash.com/photo-1528702748617-c64d49f918af?w=400&h=300&fit=crop",
    date: "Sat, Aug 16 · 9:00 AM",
    location: "Hyde Park, London",
    fee: 25,
    spotsLeft: null,
    status: "full",
    registerHref: "/challenges/register/4",
    tags: ["CW 10k Runs", "Hyde Park", "London"],
    fundraisingGoal: 30000,
  },
  {
    id: 5,
    title: "CW Half Marathon",
    image: "https://images.unsplash.com/photo-1461897104016-0b3b00cc81ee?w=400&h=300&fit=crop",
    date: "Sun, Aug 17 · 7:30 AM",
    location: "Victoria Park, London",
    fee: 40,
    spotsLeft: 20,
    status: "available",
    registerHref: "/challenges/register/5",
    tags: ["Half Marathon", "Victoria Park", "London", "Charity Week"],
    fundraisingGoal: 75000,
  },
  {
    id: 6,
    title: "CW Cycling Challenge",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    date: "Sat, Aug 23 · 8:00 AM",
    location: "Richmond Park, London",
    fee: 35,
    spotsLeft: 3,
    status: "few",
    registerHref: "/challenges/register/6",
    tags: ["Cycling", "Richmond Park", "London", "Charity Week"],
    fundraisingGoal: 60000,
  },
];
